name: Obtener IP

on: [push]

jobs:
  get-ip:
    runs-on: windows-latest
    
    steps:
    - name: Obtener IP
      run: |
        $response = Invoke-WebRequest -Uri "https://ifconfig.co"
        $ip = $response.Content
        Write-Host "Mi dirección IP es $ip"
